---
proxies:
- name: TROJAN 1
  type: trojan
  server: id-atha.bypass.id
  port: 443
  password: 4e5ac940-3a4c-11ec-8e95-1577c1651679
  udp: true
  sni: login5.spotify.com
  skip-cert-verify: true
  
- name: TROJAN 2
  type: trojan
  server: id-biznet.bypass.id
  port: 443
  password: ffbbe1c0-0b74-11ec-8f74-1577c1651679
  udp: true
  sni: login5.spotify.com
  skip-cert-verify: true
  
- name: TROJAN 3
  type: trojan
  server: id-kreatif.bypass.id
  port: 443
  password: 4dc25100-565e-11ec-bf09-1577c1651679
  udp: true
  sni: login5.spotify.com
  skip-cert-verify: true
  
- name: TROJAN 4
  type: trojan
  server: id-awan.bypass.id
  port: 443
  password: 8c8d01c0-565e-11ec-a5b7-1577c1651679
  udp: true
  sni: login5.spotify.com
  skip-cert-verify: true
proxy-groups:
- name: Gaming
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - TROJAN 3
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Umum
  type: url-test
  disable-udp: false
  proxies:
  - TROJAN 1
  - TROJAN 2
  - TROJAN 3
  - TROJAN 4
  health-check:
  enable: true
  interval: 600
  lazy: true
  url: http://www.gstatic.com/generate_204
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: bams
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7874
  nameserver:
  - 8.8.8.8
  - 8.8.4.4
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
  default-nameserver:
  - 8.8.8.8
  - 8.8.4.4
ipv6: false
profile:
  store-selected: true
rules:
- RULE-SET,google-ads,REJECT
- RULE-SET,ads,REJECT
- RULE-SET,adaway,REJECT
- RULE-SET,Umum,Umum
- RULE-SET,Gaming,Gaming
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,GLOBAL
rule-providers:
  Umum:
    type: file
    behavior: classical
    path: "./rule_provider/umum.yaml"
  Gaming:
    type: file
    behavior: classical
    path: "./rule_provider/gaming.yaml"
  adaway:
    type: file
    behavior: classical
    path: "./rule_provider/adaway.yaml"
  ads:
    type: file
    behavior: classical
    path: "./rule_provider/ads.yaml"
  google-ads:
    type: file
    behavior: classical
    path: "./rule_provider/google_video_ads.yaml"
tproxy-port: 7895
tun:
  enable: true
  stack: system
  dns-hijack:
  - tcp://8.8.8.8:53
  - tcp://8.8.4.4:53
